package com.ui.drawer;

public enum SubMenuEnum
{
    //ORDER
    PLACE_AN_ORDER,
    ACTIVE_ORDERS,
    ORDER_HISTORY,
    //MY ACCOUNT
    MY_PROFILE,
    NOTIFICATIONS,
    RIDER_REWARDS,
    DEACTIVATE_MY_ACCOUNT,
    //RETAIL
    SHOP_ONLINE,
    //INFORMATION
    FAQS,
    GIVE_FEEDBACK,
    PRIVACY_AND_SECURITY_STATEMENT,
    DO_NOT_SELL_MY_PERSONAL_INFORMATION,
    TERMS_OF_USE,
    ABOUT,
    CONTACT_CUSTOMER_SERVICE,
    //NOTHING
    NONE
}
